- name: Install mongodb component
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install npm packages
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
  - name: start and enable the mongod service
    ansible.builtin.service:
      name: mongodb-org
      state: started
      enabled: yes
      
